package com.ses.mylifeconduit.goalsetting.domain.event;

import com.ses.mylifeconduit.core.ddd.DomainEvent;
import com.ses.mylifeconduit.core.tenant.TenantId;
import com.ses.mylifeconduit.core.user.UserId;
import com.ses.mylifeconduit.goalsetting.domain.vo.GoalId; // Import GoalId

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Event indicating a ONE_YEAR goal was marked as a priority.
 */
public record PriorityGoalSelected(
        UUID eventId,
        UserId aggregateId,
        TenantId tenantId,
        long aggregateVersion,
        Instant occurredOn,
        // Event specific payload:
        GoalId goalId // The ID of the goal marked as priority
) implements DomainEvent {

    public static final String EVENT_VERSION = "V1";

    /** Canonical constructor validating inputs. */
    public PriorityGoalSelected {
        Objects.requireNonNull(eventId, "eventId cannot be null");
        Objects.requireNonNull(aggregateId, "aggregateId cannot be null");
        Objects.requireNonNull(tenantId, "tenantId cannot be null");
        if (aggregateVersion <= 0) throw new IllegalArgumentException("aggregateVersion must be positive");
        Objects.requireNonNull(occurredOn, "occurredOn cannot be null");
        Objects.requireNonNull(goalId, "goalId cannot be null");
    }

    @Override
    public String eventVersion() {
        return EVENT_VERSION;
    }
    // equals, hashCode, toString are generated by the record
}