package com.ses.mylifeconduit.goalsetting.domain.vo;

import com.ses.mylifeconduit.core.ddd.EntityId; // Use EntityId as it identifies a Goal *within* the aggregate's map
import java.util.Objects;
import java.util.UUID;

/**
 * Represents the strongly-typed identifier for a specific Goal
 * within the UserGoalSettings aggregate.
 * Implements EntityId marker interface.
 */
public final record GoalId(UUID value) implements EntityId {

    /**
     * Creates a GoalId.
     * @param value The UUID value. Cannot be null.
     */
    public GoalId {
        Objects.requireNonNull(value, "GoalId value cannot be null");
    }

    /**
     * Generates a new random GoalId.
     * @return A new GoalId.
     */
    public static GoalId generate() {
        return new GoalId(UUID.randomUUID());
    }

    /**
     * Creates a GoalId from a string representation.
     * @param uuidString The UUID string.
     * @return A GoalId.
     * @throws NullPointerException if uuidString is null.
     * @throws IllegalArgumentException if string is not a valid UUID.
     */
    public static GoalId fromString(String uuidString) {
        Objects.requireNonNull(uuidString, "UUID string cannot be null");
        return new GoalId(UUID.fromString(uuidString));
    }

    @Override
    public UUID value() { // Explicitly implement EntityId method contract
        return value;
    }

    @Override
    public String toString() {
        return value.toString();
    }
    // equals() and hashCode() are automatically generated by the record
}